version: "3.3"

services:
  database:
    container_name: postgres_db
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: docker

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"