version: "3.3"

services:
  database:
    container_name: postgres_db
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ~/smurf/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: docker

  adminer:
    container_name: postgres_admin
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8322:8080"

  rest-api:
    container_name: smurf_rest
    dns: 127.0.0.1
    build:
      context: .
      dockerfile: rest-api/Dockerfile
    ports:
      - "32280:8080"
